import {db,showPage} from "./common.js";
import {PERIOD_TIMES,slotId} from "./attendance_policy.js";
import {deleteField,doc,getDoc,updateDoc} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
const scheduleSelect=document.getElementById("scheduleDocument"),lectureSelect=document.getElementById("lectureSelect"),start=document.getElementById("startTime"),end=document.getElementById("endTime"),defaultNode=document.getElementById("defaultTime");let entries=[];
async function load(){const snap=await getDoc(doc(db,"schedule",scheduleSelect.value));entries=[];for(const day of snap.data()?.allDays||[])for(const item of day.schedules||[]){const periodNumber=Number.parseInt(item.period,10);const id=slotId(scheduleSelect.value,day.date,periodNumber,item.subject);entries.push({id,date:day.date,...item,periodNumber})}lectureSelect.innerHTML=entries.map((item,index)=>`<option value="${index}">${item.date} ${item.period} ${item.subject}${item.classGroup?`（${item.classGroup}）`:""}</option>`).join("");await selectEntry()}
async function selectEntry(){const item=entries[Number(lectureSelect.value)];if(!item)return;const defaults=PERIOD_TIMES[item.periodNumber]||{};const app=await getDoc(doc(db,"system","app"));const value=app.data()?.attendanceOverrides?.[item.id]||{};start.value=value.startTime||item.startTime||defaults.startTime||"";end.value=value.endTime||item.endTime||defaults.endTime||"";defaultNode.textContent=`標準 ${defaults.startTime||"未設定"}〜${defaults.endTime||"未設定"}`}
document.getElementById("saveOverride").onclick=async()=>{const item=entries[Number(lectureSelect.value)];if(!item||!start.value||!end.value||start.value>=end.value){alert("正しい開始・終了時刻を入力してください");return}await updateDoc(doc(db,"system","app"),{[`attendanceOverrides.${item.id}`]:{scheduleId:scheduleSelect.value,date:item.date,period:item.periodNumber,subject:item.subject,classGroup:item.classGroup||"",startTime:start.value,endTime:end.value,updatedAt:new Date().toISOString()}});alert("保存しました")};
document.getElementById("deleteOverride").onclick=async()=>{const item=entries[Number(lectureSelect.value)];if(!item)return;await updateDoc(doc(db,"system","app"),{[`attendanceOverrides.${item.id}`]:deleteField()});await selectEntry();alert("標準時刻に戻しました")};
scheduleSelect.onchange=load;lectureSelect.onchange=selectEntry;document.getElementById("backButton").onclick=()=>history.back();load().catch(error=>alert(error.message));showPage();
