import {auth,setupTheme,initializePage,loadProfileImage,loadUserName,setupAdminTab} from "./common.js";
import {getIdTokenResult} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
const $=id=>document.getElementById(id),roleName={administrator:"病院管理者",doctor:"医師",nurse:"看護師",pharmacist:"薬剤師",pt:"理学療法士",ot:"作業療法士",st:"言語聴覚士",clerk:"医事・受付",auditor:"監査担当"};
setupTheme($("themeButton"));await initializePage([setupAdminTab(),loadUserName($("userName")),loadProfileImage($("topProfileImage"))]);
const token=auth.currentUser?await getIdTokenResult(auth.currentUser):null,claims=token?.claims||{};if(claims.clinical!==true){$("workspace").innerHTML='<div class="clinical-empty">Clinicalへログインしてから開いてください。</div>';throw new Error("Clinical login required")}
const role=String(claims.clinicalRole||""),hospitalId=String(claims.clinicalHospitalId||"");$("roleLabel").textContent=`${roleName[role]||"Clinical職員"} ・ ${hospitalId}`;
const canManage=["administrator","clerk"].includes(role),canOrder=["administrator","doctor"].includes(role),canRecord=["administrator","doctor","nurse","pharmacist","pt","ot","st"].includes(role);if(canManage)$("addPatient").classList.remove("hidden");
let patients=[{id:"CASE-001",label:"検証ケース 001",department:"内科",status:"入院中",summary:"検証用の患者サマリーです。",vitals:[36.4,36.6,36.5,36.7],records:[{role:"nurse",title:"看護記録",body:"観察・ケア記録（検証用）",time:"本日 09:00"}],orders:"点滴・検査・処置の指示は医師または病院管理者のみ編集できます。",schedule:"10:00 検査予定\n14:00 リハビリ予定"},{id:"CASE-002",label:"検証ケース 002",department:"整形外科",status:"外来",summary:"検証用の患者サマリーです。",vitals:[36.2,36.4,36.3,36.5],records:[],orders:"指示は未登録です。",schedule:"予定は未登録です。"}],selectedId="CASE-001",tab="overview";
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));const selected=()=>patients.find(p=>p.id===selectedId);
function renderPatients(){const q=$("patientSearch").value.trim().toLowerCase();$("patientList").innerHTML=patients.filter(p=>`${p.id} ${p.label}`.toLowerCase().includes(q)).map(p=>`<button class="clinical-patient ${p.id===selectedId?"active":""}" data-patient="${p.id}"><b>${esc(p.label)}</b><small>${esc(p.id)} ・ ${esc(p.department)} ・ ${esc(p.status)}</small></button>`).join("")||"<small>該当するケースはありません。</small>"}
function tabs(){return `<div class="clinical-tabs">${[["overview","患者サマリー"],["records","多職種カルテ"],["orders","指示・予定"],["charts","グラフ・データ"],["audit","監査・書き出し"]].map(([id,label])=>`<button class="${tab===id?"active":""}" data-tab="${id}">${label}</button>`).join("")}</div>`}
function panel(p){if(tab==="overview")return `<h3>患者サマリー</h3><p>${esc(p.summary)}</p><div class="clinical-data-grid"><div class="card"><small>患者区分</small><b>${esc(p.status)}</b></div><div class="card"><small>診療科</small><b>${esc(p.department)}</b></div><div class="card"><small>記録件数</small><b>${p.records.length}件</b></div><div class="card"><small>現在の閲覧者</small><b>${roleName[role]||"職員"}</b></div></div>`;if(tab==="records")return `<h3>多職種カルテ</h3>${canRecord?`<form id="recordForm"><label>記録タイトル<input id="recordTitle" maxlength="120" placeholder="例：本日の経過記録"></label><label>内容<textarea id="recordBody" rows="5" maxlength="3000" placeholder="SOAP・経過・評価を入力"></textarea></label><button class="btn btn-primary">${roleName[role]}として記録を追加</button></form>`:'<p class="clinical-notice">この職種は記録の閲覧のみです。</p>'}<div>${p.records.map(r=>`<article class="clinical-entry"><small>${esc(roleName[r.role]||r.role)} ・ ${esc(r.time)}</small><br><b>${esc(r.title)}</b><p>${esc(r.body)}</p></article>`).join("")||"<p>記録はありません。</p>"}</div>`;if(tab==="orders")return `<h3>指示・予定</h3><label>診療・処置・薬剤等の指示<textarea id="ordersText" rows="6" ${canOrder?"":"readonly"}>${esc(p.orders)}</textarea></label>${canOrder?'<button id="saveOrders" class="btn btn-primary">指示を更新</button>':'<p class="clinical-note">指示は閲覧できますが、編集できるのは医師と病院管理者だけです。</p>'}<label>検査・処置・リハビリ等の予定<textarea id="scheduleText" rows="5" ${canManage||canOrder?"":"readonly"}>${esc(p.schedule)}</textarea></label>${canManage||canOrder?'<button id="saveSchedule" class="btn btn-secondary">予定を更新</button>':'<p class="clinical-note">予定は閲覧のみです。</p>'}`;if(tab==="charts")return `<h3>グラフ・データ</h3><p class="clinical-note">検証ケースの体温推移</p><div class="clinical-chart">${p.vitals.map(v=>`<i style="height:${Math.max(8,Math.min(100,(v-34)*20))}%" title="${v}℃"></i>`).join("")}</div><p>${p.vitals.map(v=>`${v}℃`).join(" ／ ")}</p>`;return `<h3>監査・書き出し</h3><p>記録の閲覧・変更・確定・出力は、本番版では利用者ID・日時・対象・操作内容を監査対象にします。</p><button class="btn btn-secondary" disabled>書き出しは安全基盤の整備後に有効化</button>`}
function render(){const p=selected();renderPatients();$("workspace").innerHTML=`<div class="clinical-patient-head"><div><h2>${esc(p.label)}</h2><small>${esc(p.id)}</small><div class="clinical-badges"><span class="clinical-badge">${esc(p.department)}</span><span class="clinical-badge">${esc(p.status)}</span></div></div></div>${tabs()}<div id="panel">${panel(p)}</div>`}
$("patientSearch").oninput=renderPatients;$("addPatient").onclick=()=>{const id=`CASE-${String(patients.length+1).padStart(3,"0")}`;patients.push({id,label:`検証ケース ${id.slice(-3)}`,department:"未設定",status:"受付",summary:"検証ケースです。",vitals:[],records:[],orders:"指示は未登録です。",schedule:"予定は未登録です。"});selectedId=id;render()};document.addEventListener("click",e=>{const patient=e.target.closest("[data-patient]"),nextTab=e.target.closest("[data-tab]");if(patient){selectedId=patient.dataset.patient;render();return}if(nextTab){tab=nextTab.dataset.tab;render();return}const p=selected();if(e.target.id==="saveOrders"){p.orders=$("ordersText").value;render()}if(e.target.id==="saveSchedule"){p.schedule=$("scheduleText").value;render()}});document.addEventListener("submit",e=>{if(e.target.id!=="recordForm")return;e.preventDefault();const title=$("recordTitle").value.trim(),body=$("recordBody").value.trim();if(!body)return;selected().records.unshift({role,title:title||"無題の記録",body,time:"保存直後"});render()});render();
