import {db,studentNumber,setupTheme,initializePage,loadProfileImage,loadUserName,loadMyRanking,setupAdminTab} from "./common.js";
import {collection,doc,addDoc,setDoc,updateDoc,deleteDoc,onSnapshot,query,orderBy,serverTimestamp,getDocs} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
const OWNER="2510044", roles={doctor:"医師",nurse:"看護師",pharmacist:"薬剤師",pt:"PT",ot:"OT",st:"ST",clerk:"医事・受付"};
const $=id=>document.getElementById(id), main=$("clinicalMain"), patientList=$("patientList");let patients=[],selected=null,records=[],tab="summary",stopRecords=null;
setupTheme($("themeButton"));await initializePage([setupAdminTab(),loadUserName($("userName")),loadMyRanking(),loadProfileImage($("topProfileImage"))]);
if(studentNumber!==OWNER){main.innerHTML='<div class="chart-empty">この機能は2510044専用です。</div>';patientList.innerHTML="";throw new Error("Unauthorized clinical training access");}
const patientRef=collection(db,"clinicalTraining",OWNER,"patients");
onSnapshot(query(patientRef,orderBy("updatedAt","desc")),snap=>{patients=snap.docs.map(d=>({id:d.id,...d.data()}));if(selected&&!patients.some(x=>x.id===selected.id))selectPatient(null);else if(selected)selected=patients.find(x=>x.id===selected.id);renderPatients();render();},e=>{console.error(e);patientList.textContent="患者一覧を読み込めませんでした。"});
function esc(v){return String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"})[c])}function date(v){return v?.toDate?v.toDate().toLocaleString("ja-JP"):"保存直後"}
function renderPatients(){const key=$("patientSearch").value.trim().toLowerCase();const rows=patients.filter(p=>!key||`${p.name} ${p.patientId}`.toLowerCase().includes(key));patientList.innerHTML=rows.length?rows.map(p=>`<button class="patient-item ${selected?.id===p.id?"active":""}" data-patient="${p.id}"><b>${esc(p.name)}</b><small>${esc(p.patientId)} ・ ${esc(p.department||"未設定")}</small></button>`).join(""):"<small>該当する患者はいません。</small>"}
function selectPatient(p){selected=p;records=[];if(stopRecords)stopRecords();if(p)stopRecords=onSnapshot(query(collection(db,"clinicalTraining",OWNER,"patients",p.id,"records"),orderBy("createdAt","desc")),s=>{records=s.docs.map(d=>({id:d.id,...d.data()}));render();},e=>{console.error(e);records=[];render()});renderPatients();render()}
function tabs(){return `<div class="clinical-tabs">${[["summary","サマリー"],["record","記録を書く"],["timeline","経過"],["charts","グラフ"],["export","書き出し"]].map(([id,label])=>`<button data-tab="${id}" class="${tab===id?"active":""}">${label}</button>`).join("")}</div>`}
function render(){if(!selected){main.innerHTML='<div class="chart-empty">左の「架空患者を登録」から始めてください。</div>';return}const allergy=selected.allergy?`<span class="badge danger-badge">アレルギー：${esc(selected.allergy)}</span>`:"";main.innerHTML=`<div class="patient-header"><div><h2>${esc(selected.name)}</h2><small>${esc(selected.patientId)} ・ ${esc(selected.gender||"性別未設定")} ・ ${esc(selected.birthDate||"生年月日未設定")}</small><div class="patient-badges"><span class="badge">${esc(selected.department||"診療科未設定")}</span>${allergy}${selected.diagnosis?`<span class="badge">主病名：${esc(selected.diagnosis)}</span>`:""}</div></div><button id="deletePatient" class="btn btn-danger">患者を削除</button></div><hr>${tabs()}<div id="tabPanel"></div>`;const panel=$("tabPanel");if(tab==="summary")panel.innerHTML=summary();if(tab==="record")panel.innerHTML=recordForm();if(tab==="timeline")panel.innerHTML=timeline();if(tab==="charts")panel.innerHTML=charts();if(tab==="export")panel.innerHTML=exportPanel()}
function summary(){const latest=records[0];return `<section><h3>患者サマリー</h3><p>${esc(selected.summary||"サマリーは未入力です。患者情報の編集から追加できます。")}</p><div class="vitals"><div class="card"><small>身長</small><b>${esc(selected.height||"—")} cm</b></div><div class="card"><small>体重</small><b>${esc(selected.weight||"—")} kg</b></div><div class="card"><small>血液型</small><b>${esc(selected.bloodType||"—")}</b></div><div class="card"><small>最終記録</small><b>${latest?date(latest.createdAt):"—"}</b></div></div><p style="margin-top:16px"><button id="editPatient" class="btn btn-secondary">患者情報を編集</button></p></section>`}
function recordForm(){return `<section class="record-form"><h3>多職種記録</h3><label>職種<select id="recordRole">${Object.entries(roles).map(([k,v])=>`<option value="${k}">${v}</option>`).join("")}</select></label><label>記録タイトル<input id="recordTitle" maxlength="120" placeholder="例：午前の看護記録"></label><label>内容（SOAP・経過・評価など）<textarea id="recordBody" rows="8" maxlength="5000" placeholder="S：\nO：\nA：\nP："></textarea></label><div class="vitals"><label>体温（℃）<input id="vitalTemp" inputmode="decimal"></label><label>脈拍（回/分）<input id="vitalPulse" inputmode="numeric"></label><label>収縮期BP<input id="vitalSys" inputmode="numeric"></label><label>拡張期BP<input id="vitalDia" inputmode="numeric"></label></div><button id="saveRecord" class="btn btn-primary">記録を保存</button></section>`}
function timeline(){return `<section><h3>経過タイムライン</h3>${records.length?records.map(r=>`<article class="record-line"><div class="meta"><span class="role">${roles[r.role]||"記録者"}</span> ・ ${date(r.createdAt)}</div><b>${esc(r.title||"無題の記録")}</b><p>${esc(r.body||"").replace(/\n/g,"<br>")}</p>${r.vitals&&Object.values(r.vitals).some(Boolean)?`<small>体温 ${esc(r.vitals.temp||"—")}℃ ／ 脈拍 ${esc(r.vitals.pulse||"—")} ／ BP ${esc(r.vitals.sys||"—")}/${esc(r.vitals.dia||"—")}</small>`:""}</article>`).join(""):"<p>まだ記録はありません。</p>"}</section>`}
function charts(){const values=records.slice().reverse().filter(r=>Number(r.vitals?.temp)>0).slice(-12);return `<section><h3>バイタル推移：体温</h3>${values.length?`<div class="chart">${values.map(r=>{const v=Number(r.vitals.temp);return `<i style="height:${Math.max(8,Math.min(100,(v-34)*20))}%"><span>${v}℃</span></i>`}).join("")}</div><small>直近${values.length}件。体温の入力がある記録のみ表示します。</small>`:'<div class="chart-empty">体温を入力した記録を保存するとグラフになります。</div>'}</section>`}
function exportPanel(){return `<section><h3>データ書き出し</h3><p>患者情報と多職種記録を、学習用データとして端末へ書き出せます。</p><button id="downloadJson" class="btn btn-primary">JSONで書き出す</button> <button id="downloadCsv" class="btn btn-secondary">CSVで書き出す</button></section>`}
function download(name,type,body){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([body],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("newPatientButton").onclick=()=>{main.innerHTML=`<h2>架空患者を登録</h2><form id="patientForm" class="record-form"><label>患者ID<input name="patientId" required maxlength="40" placeholder="例：CM-0001"></label><label>氏名（架空）<input name="name" required maxlength="80" placeholder="例：佐藤 花子"></label><div class="vitals"><label>生年月日<input name="birthDate" type="date"></label><label>性別<input name="gender" placeholder="例：女性"></label><label>診療科<input name="department" placeholder="例：内科"></label><label>血液型<input name="bloodType" placeholder="例：A型"></label></div><label>主病名<input name="diagnosis" maxlength="120"></label><label>アレルギー<input name="allergy" maxlength="120"></label><label>サマリー<textarea name="summary" rows="5"></textarea></label><button class="btn btn-primary">登録する</button></form>`;$("patientForm").onsubmit=async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e.target));const d=await addDoc(patientRef,{...x,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),trainingOnly:true});selectPatient({id:d.id,...x})}}
$("patientSearch").oninput=renderPatients;document.addEventListener("click",async e=>{const p=e.target.closest("[data-patient]");if(p)return selectPatient(patients.find(x=>x.id===p.dataset.patient));const t=e.target.closest("[data-tab]");if(t){tab=t.dataset.tab;render();return}if(e.target.id==="saveRecord"){const body=$("recordBody").value.trim(),title=$("recordTitle").value.trim();if(!body)return alert("記録内容を入力してください。");await addDoc(collection(db,"clinicalTraining",OWNER,"patients",selected.id,"records"),{role:$("recordRole").value,title,body,vitals:{temp:$("vitalTemp").value,pulse:$("vitalPulse").value,sys:$("vitalSys").value,dia:$("vitalDia").value},createdAt:serverTimestamp()});await updateDoc(doc(patientRef,selected.id),{updatedAt:serverTimestamp()});alert("記録を保存しました。");return}if(e.target.id==="deletePatient"){if(confirm("この架空患者と記録を削除しますか？")){await deleteDoc(doc(patientRef,selected.id));selectPatient(null)}return}if(e.target.id==="editPatient"){const next=prompt("患者サマリーを編集",selected.summary||"");if(next!==null)await updateDoc(doc(patientRef,selected.id),{summary:next,updatedAt:serverTimestamp()});return}if(e.target.id==="downloadJson"){download(`${selected.patientId}_caremate_training.json`,`application/json`,JSON.stringify({patient:selected,records},null,2));return}if(e.target.id==="downloadCsv"){const head="日時,職種,タイトル,内容,体温,脈拍,収縮期BP,拡張期BP";const rows=records.map(r=>[date(r.createdAt),roles[r.role]||"",r.title||"",r.body||"",r.vitals?.temp||"",r.vitals?.pulse||"",r.vitals?.sys||"",r.vitals?.dia||""].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(","));download(`${selected.patientId}_caremate_training.csv`,`text/csv;charset=utf-8`,`\uFEFF${[head,...rows].join("\n")}`)}});
