import { studentNumber, functions, auth, setupTheme, initializePage, loadProfileImage, loadUserName, setupAdminTab } from "./common.js";
import { httpsCallable } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-functions.js";
import { getIdTokenResult } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
const $=id=>document.getElementById(id);setupTheme($("themeButton"));await initializePage([setupAdminTab(),loadUserName($("userName")),loadProfileImage($("topProfileImage"))]);
const clinicalClaims=auth.currentUser?await getIdTokenResult(auth.currentUser):null;const systemOwner=studentNumber==="2510044";const hospitalAdministrator=clinicalClaims?.claims?.clinical===true&&clinicalClaims.claims.clinicalRole==="administrator";if(!systemOwner&&!hospitalAdministrator){document.querySelector("main").innerHTML='<section class="card setting-card">この画面はClinical管理者だけが利用できます。</section>';throw new Error("Clinical admin only");}
document.querySelector("main").insertAdjacentHTML("afterbegin",'<section class="card setting-card"><h2>病院アカウント</h2><p><small>最初に作成した一病院だけを登録します。患者データと職員設定はこの病院に継続して保管されます。</small></p><form id="hospitalForm"><label>病院名<input id="hospitalName" required maxlength="120" placeholder="例：CareMate総合病院"></label><label>病院ID<input id="newHospitalId" required maxlength="80" placeholder="例：caremate-hospital"></label><label>病院管理者の職員ID<input id="administratorId" required inputmode="numeric" maxlength="7" placeholder="例：2510044"></label><button class="btn btn-primary">病院アカウントを作成</button></form><p id="hospitalStatus" aria-live="polite"></p></section>");
document.querySelector('#staffRole option[value="administrator"]')?.remove();
$("hospitalForm").onsubmit=async e=>{e.preventDefault();const status=$("hospitalStatus"),button=e.submitter;button.disabled=true;status.textContent="病院アカウントを作成中…";try{await httpsCallable(functions,"createClinicalHospital")({hospitalName:$("hospitalName").value.trim(),hospitalId:$("newHospitalId").value.trim(),administratorId:$("administratorId").value.trim()});status.textContent="病院アカウントを作成しました。病院管理者はClinicalへログインし直してください。"}catch(error){console.error(error);status.textContent=error.code==="functions/already-exists"?"すでに病院アカウントがあります。削除または移管が完了するまで新規作成できません。":"病院アカウントを作成できませんでした。病院IDと管理者の職員IDを確認してください。"}finally{button.disabled=false}};
if(!systemOwner)document.getElementById("hospitalForm").closest("section").hidden=true;
$("staffForm").onsubmit=async e=>{e.preventDefault();const status=$("staffStatus"),button=e.submitter;button.disabled=true;status.textContent="権限を設定中…";try{await httpsCallable(functions,"configureClinicalStaff")({hospitalId:$("hospitalId").value.trim(),staffId:$("staffUid").value.trim(),role:$("staffRole").value,active:true});status.textContent="職員権限を設定しました。対象職員は次回ログイン時から有効になります。"}catch(error){console.error(error);status.textContent=error.code==="functions/not-found"?"その職員IDのCareMateアカウントがまだ登録されていません。先にアカウントを作成してください。":"設定できませんでした。施設ID・職員ID・管理者ログインを確認してください。"}finally{button.disabled=false}};
